# Generated by Django 6.0.3 on 2026-03-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_booking_booking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, help_text='Rich storytelling about the city vibe', null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='tagline',
            field=models.CharField(blank=True, help_text='e.g., The Silicon Valley of India', max_length=255, null=True),
        ),
    ]
